version: '2'
services:
  kafka-manager:
    image: sheepkiller/kafka-manager      
    environment:
      ZK_HOSTS: 127.0.0.1:2181
      APPLICATION_SECRET: "br2019"
    ports:
      - "39000:9000"
    expose:
      - "9000"
